### ISSUE TITLE
Prvi pregled

### ISSUE THREAD

**Issue by MiranBrumec** [MUYUM/eGeodetskiNacrt#1]
Najprej pohvala. Velik napredek. Dodajam nekaj detajlov za premislek.
V skupini 6 so 1 - parcelne meje (na skici manjkajo objekti 61). Predlagam, da pripišete še 2 - dejanska raba in 3 - namenska raba. Verjetno bo potrebna podrobnejša delitev dejanskih rab, če še niso usklajene.
Točke bi naj imele polja: Oznaka, E, N, **DRMS** (s2D), H, **SigmaH** (s1D), **OznačitevID** (TipID), Pomen, **Datum** in Projekt, kar pomeni skorajšnjo skladnost z vašim modelom.
Pri parcelnih mejah imamo opravka s točkami katastra nepremičnin (KN) in izmerjenimi katastrskimi točkami. Včasih se razlikujejo do 0,25 m zaradi transformacije, zaradi nepopravljanja koordinat ali izjemoma zaradi premika točk. Z izračunanimi katastrskimi točkami, ki jih dobimo s preračunom in transformacijo, si pomagamo pri homogenizaciji.
Pravilnik predvideva homogenizacijo slojev GJI, DR, NR, KN na osnovi izmerjenih in drugih kakovostnih točk. Pri tem koraku se mnogim zatika. Praviloma ga izpustijo, ali ga zreducirajo na t.i. lokacijsko izboljšavo grafike KN.
Lep pozdrav

**Comment by MUYUM** [comment]
Zdravo Miran

Posodobil sem specifikacijo. Pod spremembo (48afa96) sem dodal:
- Sloje "Namenska raba" in "Dejanska raba"
- Oznaka točk

Glede transformacij in drugih postopkov KN menimo, da gre za tehnične postopke, ki niso vezani na specifikacijo  eGeodetskiNacrt. Geodet izdela "lokacijsko izboljšavo" na podlagi svojih izkušenj/programov/postopkov, nato izboljšano stanje zapiše v eGeodetskiNačrt, kjer navede, da gre za sloj "Parcelne meje" in vsaki točki doda natančnost.

LP

**Comment by MUYUM** [comment]
Spremembe sprejete

**Comment by MiranBrumec** [comment]
https://repozitorij.uni-lj.si/Dokument.php?id=83744&lang=slv
Na to nalogo sem se spomnil. Mogoče je še katera na to temo.
LP
